import NavBar from "./LandingPageComponents/NavBar";
import HeroSection from './LandingPageComponents/HeroSection'
import Footer from "./LandingPageComponents/Footer";
import CTASection from "./LandingPageComponents/CTAsection";
function Landing() {
  return (
    <>
    <NavBar/>
    <HeroSection/>
    <CTASection/>
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo non, nisi assumenda mollitia omnis eaque delectus nostrum culpa quas veniam nihil voluptatem, perspiciatis similique ab! Praesentium, est. Aliquid, corrupti quae!
    Voluptate, corrupti? Debitis laudantium, laborum officiis, omnis voluptates, perferendis sint at aliquam expedita amet praesentium. Architecto dignissimos doloribus nobis ab delectus, facere veniam dicta eius quod distinctio deserunt pariatur sint.
    Laboriosam hic porro, dolores eveniet vero iure velit adipisci quasi aliquam, rerum, atque labore id culpa! Fuga vel perferendis quos, inventore iste sapiente repellat incidunt maxime quod impedit, omnis officiis!
    Libero facere qui voluptatem facilis ab voluptas nesciunt laboriosam fuga? Adipisci magnam et dolorem quae doloribus nemo incidunt itaque, tempore ducimus sequi reiciendis dolor, error dicta ratione at neque sunt.
    Asperiores placeat libero inventore, cum veniam tempora perspiciatis dolorum id! Inventore, cumque aspernatur eveniet cum laborum labore nam totam doloribus obcaecati voluptatem nostrum temporibus quidem aliquid maiores facere, impedit error?
    Suscipit assumenda pariatur quas deserunt debitis dolor omnis quo? Atque neque sit nobis minima eius asperiores est ad, nihil magni adipisci vero et soluta assumenda sunt ipsum itaque tempora laboriosam!
    Explicabo expedita dicta id quasi porro tempore sunt, ut totam provident sint doloremque repellendus cumque maxime, qui quas quae culpa minus similique sit doloribus dolorum. Eius dolor velit unde sed.
    Unde ratione eligendi fuga earum, et ipsam architecto? Eveniet temporibus autem, perspiciatis ratione rerum quia saepe blanditiis, esse porro alias ex veniam, quos repellendus dolores exercitationem odit expedita doloribus itaque?
    Et suscipit laudantium sit aspernatur delectus quaerat nam, similique quasi eos maiores veritatis repellendus quo temporibus quidem sequi. Debitis aliquid vero veniam aperiam cum velit odio eius natus aut minima!
    Sunt, eaque enim nobis voluptatem blanditiis debitis neque perspiciatis repudiandae harum nihil laborum molestias nam! Sequi dolores vel quae dolorum vero odio deleniti, similique maiores dolorem, numquam et doloribus accusantium!
    Aut earum corrupti pariatur aspernatur cum, dolorum laboriosam! Repudiandae rerum id rem placeat, vel asperiores voluptatibus nam alias, ullam in animi explicabo molestiae ea, nemo architecto facilis autem suscipit nesciunt?
    Culpa ad totam aspernatur, fugiat inventore repellendus est mollitia necessitatibus alias rerum architecto aperiam nihil aut sequi ducimus vitae praesentium accusantium nostrum sit ex expedita facilis repudiandae perferendis? Placeat, cupiditate.
    Debitis et magnam blanditiis, quae accusantium, animi deserunt tenetur, velit cum tempora mollitia. Dolores eaque ea magnam provident voluptatum quo, atque, molestias animi autem, optio quibusdam perferendis excepturi eum vitae?
    Vel praesentium quod dolores ab molestiae tempora ipsam, maiores, iusto quis explicabo nihil doloremque nam vitae odio odit blanditiis, cum labore hic iure animi fugiat adipisci consequuntur perspiciatis architecto? Suscipit.
    Totam unde accusantium provident. Quasi delectus nam itaque sunt repudiandae amet pariatur ea accusantium, ullam dignissimos odit at sint sequi reiciendis quos iure vel minus architecto eos laborum dolorem! Amet.
    Earum tempora pariatur placeat delectus incidunt odit! Culpa id vero illo vel iste. Optio commodi pariatur, doloremque ad laborum, culpa nemo quos non animi, ea quia quo! Laborum, accusantium obcaecati?
    Distinctio possimus pariatur voluptatibus, vero corrupti excepturi tenetur eum dicta expedita modi necessitatibus, illo ea consequuntur nemo iste quo amet delectus mollitia laborum reiciendis doloribus? Adipisci consequuntur hic vero aliquam!
    Accusamus sit minima ea? Aut, aperiam tempore alias necessitatibus minima, corporis ut quia temporibus vitae possimus magni sint repellat nemo iste dicta distinctio velit veritatis neque? Vel ullam fugit ipsa.
    Optio velit ipsam, dignissimos hic fugiat sed sunt neque quis expedita quasi reprehenderit dolore iusto voluptas exercitationem rerum odit ullam! Vel delectus molestias eum suscipit error ex voluptate sint veritatis.
    Ex ut delectus at ipsa rerum exercitationem, suscipit sunt facere labore. Commodi, amet iusto. Reprehenderit dicta cum aliquid est nostrum quaerat molestias inventore tempore. Amet eius libero ut dignissimos excepturi.
    Distinctio illum sed libero et consequuntur incidunt itaque molestias id ea aliquam ut aliquid similique eligendi fugiat, assumenda ipsum corrupti? Aliquid dolores voluptate amet maxime itaque? Id adipisci optio itaque.
    Officia quisquam numquam quia hic commodi facere nemo? Dolorum nisi iste magni necessitatibus mollitia sed molestiae blanditiis quas. Consectetur necessitatibus deserunt sequi soluta ullam, veritatis molestias reprehenderit. Fugiat, ea aspernatur?
    Voluptas perferendis esse doloremque blanditiis ipsa quo adipisci consectetur culpa ut deleniti dolor iusto id fugit numquam molestiae sapiente inventore possimus, aut quas laborum. Magnam iure a facere magni ut.
    Ea sunt distinctio laborum nisi perspiciatis nulla atque impedit nostrum dolorum sed necessitatibus delectus ipsa maxime reprehenderit consequuntur inventore vero eum fugiat, quibusdam autem dignissimos culpa dolorem cumque esse. Praesentium!
    Architecto saepe velit fuga, cum dolor unde harum aperiam repellat nisi placeat nemo magni, tenetur itaque culpa ad deserunt accusamus reiciendis molestiae quia et eius! Est quasi sit quod eveniet.
    Ipsa ipsam necessitatibus a unde optio, possimus laboriosam sint, praesentium sapiente iste repellat earum minima cum vitae ducimus voluptates dolor accusantium magni velit iusto saepe molestiae iure facere adipisci! Illum.
    Odit fugiat provident laboriosam praesentium adipisci labore debitis voluptate cum esse, impedit, ab consectetur quidem nostrum nesciunt omnis. Esse quidem molestias totam suscipit neque vero delectus voluptatem sunt, iusto illo.
    Officiis minima, obcaecati ad deleniti nostrum fugit quas dignissimos mollitia velit distinctio! Doloribus nostrum rem, in, iusto commodi vel, adipisci corrupti fugiat id aut deleniti. Quo voluptates quod eaque harum!
    Ex quibusdam ipsa cum ducimus provident. Maiores repudiandae ut blanditiis aliquid nostrum provident modi sapiente! Quasi quae doloremque maiores. Illo dolore tempora possimus blanditiis laboriosam? Quaerat commodi quod ex iure?
    Adipisci in eaque aliquid culpa quam architecto. Voluptatem tenetur voluptate animi id repellat, vero repudiandae maxime facere totam earum illo placeat dicta rerum architecto eligendi excepturi voluptatum saepe nemo expedita.
    Quo natus, reiciendis, veniam quam voluptatem reprehenderit magni officia nesciunt obcaecati cum cumque recusandae est assumenda, non hic repellat unde tempore possimus culpa dignissimos. Atque totam quaerat aliquid eveniet odit.
    Ipsa, accusamus? Voluptatum tempore similique provident hic, fugiat neque sit quos illo consequuntur maxime aspernatur, expedita cum aut placeat molestias consequatur unde beatae voluptate voluptas ratione in reprehenderit? Quos, facilis.
    Cum porro eum labore, ut esse eveniet delectus neque. Voluptatibus magnam fuga repellat aut consequatur ducimus inventore quasi aliquid, harum illum facere, voluptas esse debitis labore in provident similique saepe.
    Temporibus aliquam labore ratione tenetur a, pariatur recusandae fugiat, inventore itaque delectus voluptatem rem quia consequatur eos dicta voluptas nesciunt fuga corporis minus doloremque autem laborum sequi. Hic, pariatur officia.
    Iusto quod repellendus praesentium, odio totam tempora. Dolorem tempore recusandae dolor quaerat necessitatibus cumque, adipisci maxime eos iusto aliquam dolore expedita, vitae, porro pariatur accusantium incidunt aperiam nisi officiis nostrum?
    Cupiditate, iste. Possimus provident esse delectus sequi adipisci quasi iure perferendis? Magnam provident fuga numquam dolore hic nemo necessitatibus molestias nihil, quas atque esse, quo doloribus suscipit quidem quae incidunt.
    Non eos iure doloribus enim ducimus delectus illum, aliquam recusandae vel neque minus nesciunt libero omnis odio aut nobis aliquid ex eaque dolorum. Cupiditate fugit odit neque, eius nemo nobis?
    Vero facilis numquam itaque minima nam architecto deserunt temporibus quae, aut aperiam necessitatibus illum labore obcaecati soluta quis error esse voluptas velit ducimus repudiandae modi aspernatur dolor! Minima, natus officiis.
    Magnam ad aliquam excepturi. Perferendis maiores provident facere iusto repellat distinctio sint id adipisci tenetur sapiente temporibus totam odio possimus veritatis accusantium delectus debitis, perspiciatis molestiae tempora? Libero, molestias ex!
    Eligendi animi ullam tempora maiores aliquid suscipit magnam ipsa, quaerat corporis esse reprehenderit enim excepturi dicta similique praesentium unde laborum molestiae omnis magni perspiciatis pariatur vel cumque delectus. Provident, ducimus?
    Dolore atque, ipsa eos porro itaque consequuntur expedita praesentium beatae quae facilis esse minus laudantium architecto consectetur provident non recusandae saepe deserunt tempore est ullam voluptate corporis eaque explicabo! Optio.
    Neque doloribus exercitationem, illo maxime expedita facilis dignissimos repudiandae vitae, distinctio earum fugit a ipsa dicta, dolorum ea commodi culpa quibusdam. Exercitationem impedit sed itaque, eos repellat iure rem inventore.
    Quibusdam minima quos officiis voluptas magni, distinctio, eveniet nesciunt totam fugit molestias reiciendis, omnis perferendis vel facere iste est nulla beatae. Aliquam eligendi illo sapiente quasi est autem eos sit.
    Nihil laudantium omnis dolore veritatis suscipit itaque fuga possimus, at accusantium mollitia facere tenetur totam et nemo quidem, iure dicta. Beatae autem aspernatur laboriosam doloremque neque assumenda suscipit eum consequatur!
    Ullam eaque recusandae repellat labore et velit nulla magni incidunt cum laudantium, vero possimus consequatur minus non, nobis fugiat. Reiciendis porro error neque aspernatur, tempora officiis eaque repellat at corrupti!
    Tenetur temporibus, odit repudiandae mollitia sint reprehenderit, dicta laboriosam incidunt enim cum laborum, quidem obcaecati necessitatibus qui eos sapiente soluta velit inventore sit minima natus sequi. Mollitia eius facilis veniam.
    Eius nobis tempora optio repellendus, at expedita blanditiis nulla dolorum, fugiat facilis ad delectus debitis aperiam sunt in unde eum sed nihil harum aliquam? Mollitia animi ex repudiandae numquam ipsum?
    Perferendis officia labore accusamus dolor debitis possimus earum placeat exercitationem reiciendis quibusdam illum ullam iusto ad optio eaque amet error vel quasi delectus, eum consequatur laudantium nulla. Laudantium, corporis blanditiis.
    Enim fugit molestias, omnis excepturi vero nemo iusto voluptatibus quae amet cumque soluta rerum modi error minus ipsa non facilis aut! Ad nobis ex totam libero architecto ullam asperiores repudiandae.
    Explicabo voluptas perspiciatis consequuntur error harum sint exercitationem adipisci veniam dolorum cum ipsa cupiditate repellat, ex ratione nobis nulla ipsam eius inventore debitis libero non iusto nihil tempora molestias. Rerum?
    Consequatur a pariatur eos eius, ratione provident, autem officiis sint placeat voluptatem perferendis quasi quas fugit similique repudiandae. Eum expedita itaque fuga nostrum molestias debitis hic, possimus enim sunt quam!
    Ut nam architecto odio quas minima dolorem, excepturi aut! Dignissimos perspiciatis omnis explicabo impedit aperiam est nemo eos rerum voluptatem unde quas officiis optio vero, vitae nihil saepe, voluptates possimus.
    Eligendi consequatur officiis dolores vel numquam quibusdam ipsa aliquid consectetur repudiandae. Molestias tenetur assumenda, perspiciatis nesciunt totam harum ab tempora quisquam laudantium numquam obcaecati incidunt inventore, nam saepe ea explicabo?
    Eius inventore velit omnis dolores blanditiis veniam natus nesciunt. Exercitationem fugit numquam vitae architecto magni unde cum accusantium quae, ab, quasi odio officiis quis error quo, atque enim deleniti qui.
    Cupiditate soluta veniam, perspiciatis rerum eligendi quibusdam facere! Vel aperiam enim ad consequatur deserunt quidem unde reprehenderit accusamus facilis, rem numquam rerum fugit nulla cumque eaque at expedita aut obcaecati.
    Delectus iure eveniet possimus rerum odio asperiores voluptate architecto. Cum fuga facere voluptate cupiditate quo labore provident qui, natus temporibus soluta optio architecto et ab dolor illum, deleniti molestias doloremque.
    Sunt in iure atque, fugit, neque assumenda dolorem vel dolore esse magnam nobis labore? Perferendis, nostrum eius expedita fugit sit tempore animi, veniam pariatur natus, qui totam? Alias, laudantium iste.
    Assumenda laudantium iste nesciunt perspiciatis blanditiis. Veritatis quae perspiciatis quas optio, libero beatae aut, culpa delectus expedita veniam rem eaque! Iure dolorem perspiciatis excepturi impedit quia eos fuga. Velit, dolor.
    Deleniti nam, asperiores aut corrupti nemo maiores odio eligendi quibusdam animi reiciendis consectetur, provident dicta at quae dolores laborum tenetur excepturi, quis ut delectus quod! Quaerat, ipsa culpa? Autem, at!
    Repellendus aspernatur, assumenda tempore dolor quaerat fugiat quisquam provident vero velit nemo iure nulla enim earum laudantium nam deserunt rerum eligendi voluptatibus ducimus? Deserunt, quo incidunt aspernatur expedita obcaecati saepe?
    Voluptatum incidunt doloribus tempora, quia magni impedit sit facere adipisci minus laudantium nulla obcaecati, in quibusdam asperiores voluptatibus libero corporis corrupti quae recusandae itaque! Aliquid quisquam ipsum esse laboriosam omnis.
    Impedit molestias explicabo ducimus magnam incidunt porro velit aut sapiente totam. Qui voluptatum vitae dolorum molestias tenetur illo praesentium consequatur repellendus enim eveniet officiis ipsum temporibus, minus itaque, ad ut.
    Quis sequi, vel minus quod hic cupiditate numquam, porro voluptatibus ex obcaecati dolores aliquid exercitationem nihil repellendus in soluta et quas velit. Vitae consequatur neque ipsum aliquid repellat libero velit.
    Mollitia ullam quis molestiae non tempora laboriosam laborum ex. Adipisci dolorum, ea, totam ipsam dolore distinctio sint laudantium repellat molestias eveniet facilis tempora vero amet soluta officiis repudiandae, culpa nulla?
    Praesentium, libero dicta? Incidunt nisi tempora quisquam eos a quidem tenetur libero voluptate necessitatibus, obcaecati, cum veritatis repellendus hic et earum voluptas officia quos dignissimos? Nostrum veritatis facilis atque. Est!
    Vel labore saepe voluptas molestias pariatur aliquam rerum adipisci porro sapiente sint nostrum corporis quisquam quis iste laudantium libero, deleniti minima, quo nihil quos dolorem. Veritatis incidunt obcaecati at deleniti.
    Nostrum iusto, magni incidunt quibusdam debitis natus distinctio doloremque quo dolorum sapiente consequuntur in repellendus impedit eum modi fuga minus labore dicta, illo dolores velit eveniet. Hic, voluptatum et! Ad?
    Tempore nesciunt molestiae rerum autem, obcaecati voluptatum qui quod, sed aut non voluptatibus earum amet eveniet corporis, ut necessitatibus nihil? Voluptatum, aliquam ullam? Possimus dolorum consequuntur aut facere et harum.
    Consequuntur assumenda ut soluta sed vitae dignissimos doloribus, perferendis animi sint ad blanditiis laborum sit vero earum impedit voluptas ex. Molestias laboriosam possimus soluta aut tenetur architecto expedita tempora ducimus?
    Explicabo quod temporibus commodi nam, voluptatem quos molestiae veniam maiores provident blanditiis alias aspernatur voluptates asperiores reiciendis eveniet perferendis cupiditate, unde corporis aliquid numquam harum nulla. Nam impedit alias eligendi.
    Velit aliquid atque tempore commodi quod saepe optio! Cumque sit, ea tenetur, unde corrupti id ex voluptas dignissimos atque quos eos. Quidem deleniti fuga amet temporibus, nam tenetur illum accusamus?
    At beatae nisi sunt ipsa et, unde commodi corrupti incidunt maxime non ipsum voluptatibus inventore quis exercitationem hic saepe nesciunt deserunt iusto porro vero! Corrupti facilis nemo nostrum delectus dolorum.
    Tempore non similique id corrupti totam beatae in, neque aspernatur quia aliquid vitae eos optio amet quo voluptatum dolore fugiat facilis rem libero consequuntur ipsam distinctio cupiditate vero? Esse, quidem.
    Commodi et corporis molestiae saepe veniam laudantium ratione veritatis reprehenderit illo harum? Iste nesciunt consequuntur nostrum unde, eaque, itaque eius expedita, aliquam pariatur deleniti quod amet voluptatum mollitia. A, molestias?
    Officiis expedita, nam illum consequatur fuga necessitatibus aliquid magnam repellendus praesentium, velit esse rerum dicta? Nulla vitae quo iste, quisquam exercitationem saepe, perspiciatis magni, reprehenderit at error consequatur adipisci? Totam?
    Omnis, voluptate? Quis impedit, aliquid, magnam ipsam quas fugit ipsum ducimus quaerat, debitis iure iusto. Voluptate aspernatur labore numquam minima, molestiae reiciendis nam quis, suscipit consectetur ipsum voluptates dignissimos nemo.
    Quas odit omnis explicabo reiciendis porro temporibus aliquam quos distinctio laboriosam quis molestias eum exercitationem officia, tempora rem tenetur. Quo enim, aliquid quidem et facere velit dolorum? Voluptas, numquam ea?
    Autem ullam at aliquam quos, voluptatum unde eius deleniti, a reiciendis ex ut sequi illo perferendis corrupti suscipit nam? Sed impedit laboriosam unde excepturi veritatis perspiciatis voluptas deserunt explicabo ea?
    Ab, nobis, explicabo vitae saepe, dolorem veritatis nulla ipsam perspiciatis in sint aliquid eveniet natus culpa nisi aliquam repellendus deleniti enim laborum tenetur impedit. Facere laboriosam est aut porro laudantium.
    Incidunt nostrum voluptates, qui quaerat rem repellendus ducimus? Expedita nulla praesentium mollitia, rerum ipsum obcaecati itaque totam maxime sequi sunt accusantium vitae sapiente alias libero dolorem. Similique mollitia dolorem obcaecati.
    Excepturi sint aspernatur quo magni dolore ratione mollitia ipsa blanditiis harum amet, quisquam eaque unde molestiae labore vero inventore repellat incidunt quibusdam exercitationem, neque laboriosam saepe quidem. Quam, commodi amet.
    Officia, fuga porro? Aliquid id, dolore quisquam hic quis asperiores modi eaque enim praesentium alias, aut eius reiciendis eum officiis nisi delectus facere iste, odit perferendis beatae. Dolorem, eligendi sed?
    Laboriosam blanditiis necessitatibus et! Consectetur blanditiis vero voluptatum eum placeat a totam nobis quidem veniam in molestias praesentium, explicabo ut amet iusto aspernatur ab, ex atque, velit laudantium ratione. A?
    Beatae ea quia, corrupti vitae dignissimos id, ducimus velit sapiente iste ratione assumenda excepturi non reprehenderit libero quibusdam perferendis accusantium consectetur nam rerum. Soluta non distinctio praesentium ab ratione ut.
    Alias officia repellat temporibus doloremque ipsa a, possimus nostrum voluptates reiciendis architecto cum minima nulla expedita nemo nobis, debitis, numquam commodi maxime! Fugiat, id eius neque vitae adipisci architecto ex.
    Odit, praesentium dolor hic aliquid totam non id debitis harum ipsam nam quidem accusamus optio recusandae ullam ea eveniet similique, beatae a doloribus suscipit ad. Qui temporibus distinctio incidunt totam?
    Necessitatibus harum quo omnis veritatis aliquid quis sed praesentium qui voluptate error suscipit ut quaerat architecto nulla, nisi, pariatur fugit sequi vero autem aliquam quae. Facilis nisi earum repellendus harum.
    Consequatur, optio? Labore rerum, ratione minus quam impedit eaque iusto pariatur unde, voluptates, porro sint. Fugiat dolores, officia illum sed unde earum, consequuntur doloremque atque corrupti vel beatae sit accusamus.
    Laborum repellat, tenetur suscipit quod eum minus molestiae libero, excepturi illo deserunt molestias perspiciatis sunt facere ipsum saepe a enim ullam. Quisquam eveniet amet, assumenda eius dolores repudiandae quasi hic!
    Eligendi nisi voluptate vel dicta minima aliquid deserunt veniam sed vitae praesentium reiciendis rem perferendis, provident aperiam optio assumenda. Repellat ex expedita impedit laborum veritatis accusantium. Sequi expedita consequuntur praesentium.
    Alias provident possimus ut, laudantium incidunt dignissimos vero voluptatum quasi quidem sit, esse tenetur voluptatibus asperiores. Laudantium, natus aperiam cum nam obcaecati odit mollitia eos quibusdam eum beatae omnis minima.
    Autem commodi eveniet esse quam ipsum! Expedita, dolor! Molestias quisquam ipsam voluptatibus, beatae reprehenderit odio pariatur rerum quasi velit explicabo suscipit itaque, a dignissimos nisi quis voluptate? Dolorum, unde explicabo?
    Harum obcaecati nemo qui blanditiis reprehenderit in amet culpa explicabo fuga libero rerum repellat officia, dolore saepe quam voluptatibus odio facilis. Fugit quisquam ullam necessitatibus blanditiis amet? Vel, unde nulla.
    Soluta, debitis officia eaque distinctio labore amet sint unde accusantium mollitia suscipit at quo hic nulla tempore accusamus dolor expedita iste reprehenderit impedit maiores nostrum doloribus. Possimus sequi accusamus veniam.
    Qui dolore debitis placeat perferendis ut itaque minima tenetur eum ad necessitatibus ullam obcaecati, nihil incidunt odio magnam inventore, esse, quis cupiditate vero quos architecto voluptate. A magni tenetur quos?
    Illum hic ratione aut fugit dolorum impedit, debitis pariatur recusandae, ad distinctio officiis voluptates laudantium numquam consequuntur provident ut eligendi et, iusto quisquam explicabo perferendis quasi eos minus. Cupiditate, corrupti!
    Nihil pariatur harum odio magnam, id vitae tempore saepe laudantium illum perferendis nesciunt aliquam consequatur omnis aperiam distinctio iusto officiis eligendi quod! Ratione temporibus repudiandae neque tempora enim voluptas id.
    Dicta quis adipisci nesciunt error! Nostrum, quo neque. Dignissimos sapiente dolores, accusantium saepe error ipsa quo? Reiciendis minus dolorem, eaque, numquam provident aut, tenetur architecto in sed alias repellat sunt?
    Pariatur, consequatur nemo velit sint suscipit voluptas commodi soluta quos expedita repellendus autem nulla minima omnis quas odio eligendi facilis ipsa a quo temporibus nostrum vero fuga assumenda accusantium. Minima?
    Natus harum eius illo quibusdam in quo consequuntur et nihil saepe, officia sunt impedit sint sapiente esse animi voluptatibus. Iure voluptas doloribus aut deleniti amet. Itaque quibusdam exercitationem dolorem possimus!
    <Footer/>
    </>
  );
}

export default Landing;